/*
 * strings.js — every piece of copy the site shows. Dune flavour lives here and
 * only here; swapping this file (and the colour tokens in style.css) gives a
 * plain look. No in-jokes tied to real people.
 */
export const STRINGS = {
  site: {
    title: 'Game Night Treasury',
    tagline: 'The spice must flow. So must the snacks.',
    loading: 'Opening the vault…',
    footer: 'Every rule fits in one sentence. Tap any row for details and any result for its math.',
    computed: 'Computed in your browser from the ledger on every visit.',
    skip: 'Skip to content',
  },
  nav: {
    label: 'Boards',
    month: 'Month',
    performance: 'Performance',
    wins: 'Wins',
    hall: 'Hall of Snacks',
  },
  ui: {
    expand: 'Show details',
    collapse: 'Hide details',
    backHome: 'Back to this month',
    of: 'of',
    seats: 'seats',
    meanScore: 'mean score',
    shared: 'Shared seat with',
    viewMonth: 'Open this month',
  },
  error: {
    title: 'The ledger will not open',
    intro: 'Fix the file below and reload. Nothing renders until the data is clean.',
    fetch: 'could not be loaded',
    unexpected: 'Unexpected error',
  },
  notFound: {
    title: 'Nothing buried here',
    body: 'That page does not exist in the treasury.',
  },
  month: {
    title: 'Monthly board',
    rule: 'Ten for playing, thirty for the win, sixty split by how many opponents you finished above.',
    prize: 'The month’s top score eats for free: the host buys the snacks.',
    empty: 'No games recorded this month yet. The table waits.',
    emptyNoData: 'No games recorded yet. The vault stays empty until the first night.',
    prev: 'Earlier month',
    next: 'Later month',
    podium: 'Podium',
    decidedBy: 'Tie at the top broken by',
    chartTitle: 'Race for the snacks',
    chartCaption: 'Points piled up after each game night.',
    chartStart: 'start',
    standings: 'Standings',
    results: 'Results this month',
    cols: { player: 'Player', points: 'Points', wins: 'Wins', games: 'Games' },
  },
  performance: {
    title: 'Performance',
    rule: 'Your average placement score, weighted by game, after adding ten phantom Dune games at the group’s average.',
    groupMean: 'Group average score',
    cols: { player: 'Player', p: 'Perf.', games: 'Games' },
    rawMean: 'Average before the phantom games',
    weightPlayed: 'Weight played',
    wins: 'Wins',
    empty: 'Nobody has played yet, so nobody is ranked.',
  },
  wins: {
    title: 'Wins',
    rule: 'Most wins first; equal wins are ordered by the weight of the games won.',
    filter: 'Game',
    allGames: 'All games',
    cols: { player: 'Player', wins: 'Wins', games: 'Games', weighted: 'Weighted' },
    byGame: 'Wins by game',
    none: 'No wins yet',
    empty: 'No games recorded for this filter.',
  },
  player: {
    seat: 'The {gem} seat',
    games: 'Games',
    wins: 'Wins',
    currentStreak: 'Current win streak',
    longestStreak: 'Longest win streak',
    form: 'Form, last five',
    formStates: { win: 'win', last: 'last', other: 'other' },
    formLegend: '◆ win · ○ last · ● other',
    bestGame: 'Best game',
    worstGame: 'Worst game',
    results: 'All results',
    empty: 'No games yet. A player appears on the boards after the first result.',
    cols: { date: 'Date', game: 'Game', place: 'Place', points: 'Points' },
    unknown: 'No such player.',
  },
  math: {
    title: 'The math',
    seats: 'Seats (n)',
    place: 'Place (p)',
    frac: 'Share of opponents finished above',
    floor: 'For playing',
    spread: 'Spread',
    bonus: 'Win bonus',
    score: 'Placement score',
    weight: 'Game weight',
    points: 'Points',
  },
  hall: {
    title: 'Hall of Snacks',
    rule: 'One winner a month: highest total, then most wins, then the weight of games won, then games played, then performance, then the alphabet.',
    cols: { month: 'Month', winner: 'Winner', total: 'Points', margin: 'Margin' },
    runnerUp: 'Runner-up',
    decidedBy: 'Decided by',
    noRival: 'no rival',
    tieChip: 'tie-break',
    empty: 'No month has been played yet. The first snacks are still unclaimed.',
  },
  tiebreak: [
    'highest total',
    'most wins in the month',
    'highest weight among games won',
    'most games played',
    'highest performance at month end',
    'the gem name, alphabetically',
  ],
  ordinal: { 1: 'st', 2: 'nd', 3: 'rd', other: 'th' },
  months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
};
